@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQ4NDIxNjEsImlhdCI6MTcxNDgzODU2MSwianRpIjoiNzcwMDRFNDgtN0RCNi1CREM4LUE0RDUtNkI5NEQ0NDg1MzA4IiwibmJmIjoxNzE0ODM4NTYxLCJzdWIiOjF9.vCs3uxP7GUE8kejydU1c5XDj8abQjUeH0cqrCe6Vu8o

GET http://localhost:8080/health-check HTTP/1.1
Authorization: Bearer {{token}}
