GET http://localhost:8080/health-check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQ4Mzg0NzQsImlhdCI6MTcxNDgzNDg3NCwianRpIjoiMUQ4OTlEQkQtMTAxMi03NDRGLTk1QTEtMDg5NzBGNzA3RjFEIiwibmJmIjoxNzE0ODM0ODc0LCJzdWIiOjF9.Y_vkLiadyLdXUCbjoGKZ7mtAsJ1oPsSiPM1C0opzdic
