// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	models "cep-gin-clean-arch/models"

	mock "github.com/stretchr/testify/mock"
)

// CEPRepositoryInterface is an autogenerated mock type for the CEPRepositoryInterface type
type CEPRepositoryInterface struct {
	mock.Mock
}

// Buscar provides a mock function with given fields: _a0
func (_m *CEPRepositoryInterface) Buscar(_a0 string) (models.CEPResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Buscar")
	}

	var r0 models.CEPResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.CEPResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) models.CEPResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.CEPResponse)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCEPRepositoryInterface creates a new instance of CEPRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCEPRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CEPRepositoryInterface {
	mock := &CEPRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
