package mockdb

import "cep-gin-clean-arch/models"

var CEPS = map[string]models.CEPResponse{
	"01001000": {Estado: "SP", Cidade: "São Paulo", Bairro: "Sé", Rua: "Praça da Sé"},
	"01001001": {Estado: "SP", Cidade: "São Paulo", Bairro: "Sé", Rua: "Praça da Sé"},
	"01153000": {Estado: "SP", Cidade: "São Paulo", Bairro: "Barra Funda", Rua: "Rua Vitorino Carmilo"},
	"03223050": {Estado: "SP", Cidade: "São Paulo", Bairro: "Jardim Independência", Rua: "Rua Dario Meira"},
	"03255000": {Estado: "SP", Cidade: "São Paulo", Bairro: "Vila Tolstoi", Rua: "Rua José Antônio Fontes"},
	"03513050": {Estado: "SP", Cidade: "São Paulo", Bairro: "Vila Matilde", Rua: "Rua Antônio Juvenal"},
	"03683010": {Estado: "SP", Cidade: "São Paulo", Bairro: "Vila União (Zona Leste)", Rua: "Rua Antônio Olímpio"},
	"04295001": {Estado: "SP", Cidade: "São Paulo", Bairro: "Vila Vera", Rua: "Avenida Coronel José Pires de Andrade"},
	"05425070": {Estado: "SP", Cidade: "São Paulo", Bairro: "Pinheiros", Rua: "Avenida Doutora Ruth Cardoso"},
	"05434020": {Estado: "SP", Cidade: "São Paulo", Bairro: "Vila Madalena", Rua: "Rua Morás"},
	"08090284": {Estado: "SP", Cidade: "São Paulo", Bairro: "Jardim Helena", Rua: "Rua 03 de Outubro"},
	"08410500": {Estado: "SP", Cidade: "São Paulo", Bairro: "Vila Santa Cruz (Zona Leste)", Rua: "Rua Doutor Pedro Batista"},
	"09925000": {Estado: "SP", Cidade: "Diadema", Bairro: "Campanário", Rua: "Rodovia dos Imigrantes"},
	"11441710": {Estado: "SP", Cidade: "Guarujá", Bairro: "Enseada", Rua: "Rua Projetada Nove"},
	"12209530": {Estado: "SP", Cidade: "São José dos Campos", Bairro: "Centro", Rua: "Rua José de Alencar"},
	"13327220": {Estado: "SP", Cidade: "Salto", Bairro: "Jardim Saltense", Rua: "Rua Acácio Rodrigues de Moraes"},
	"13401130": {Estado: "SP", Cidade: "Piracicaba", Bairro: "Paulista", Rua: "Rua Sud Mennucci"},
	"17022113": {Estado: "SP", Cidade: "Bauru", Bairro: "Vila São Paulo", Rua: "Rua Gaudêncio Piola"},
	"20020030": {Estado: "RJ", Cidade: "Rio de Janeiro", Bairro: "Centro", Rua: "Praça Academia"},
	"20760245": {Estado: "RJ", Cidade: "Rio de Janeiro", Bairro: "Inhaúma", Rua: "Rua José dos Reis"},
	"22610001": {Estado: "RJ", Cidade: "Rio de Janeiro", Bairro: "São Conrado", Rua: "Estrada da Gávea"},
	"23065000": {Estado: "RJ", Cidade: "Rio de Janeiro", Bairro: "Paciência", Rua: "Estrada Manguariba"},
	"23587608": {Estado: "RJ", Cidade: "Rio de Janeiro", Bairro: "Paciência", Rua: "Rua Graça e Paz"},
	"24220091": {Estado: "RJ", Cidade: "Niterói", Bairro: "Icaraí", Rua: "Rua Domingues de Sá"},
	"27913300": {Estado: "RJ", Cidade: "Macaé", Bairro: "Imbetiba", Rua: "Avenida Agenor Caldas"},
	"29010100": {Estado: "ES", Cidade: "Vitória", Bairro: "Centro", Rua: "Rua Dionísio Rosendo"},
	"29216170": {Estado: "ES", Cidade: "Guarapari", Bairro: "Praia do Morro", Rua: "Rua Saint Tropez"},
	"30150313": {Estado: "MG", Cidade: "Belo Horizonte", Bairro: "Funcionários", Rua: "Rua Ceará"},
	"30315600": {Estado: "MG", Cidade: "Belo Horizonte", Bairro: "Sion", Rua: "Rua Grão Mogol"},
	"30421052": {Estado: "MG", Cidade: "Belo Horizonte", Bairro: "Nova Suíssa", Rua: "Rua Genebra"},
	"30530000": {Estado: "MG", Cidade: "Belo Horizonte", Bairro: "João Pinheiro", Rua: "Avenida Vereador Cícero Ildefonso"},
	"31814650": {Estado: "MG", Cidade: "Belo Horizonte", Bairro: "Aarão Reis", Rua: "Rua Irmãos Rodrigues"},
	"31970420": {Estado: "MG", Cidade: "Belo Horizonte", Bairro: "Jardim Vitória", Rua: "Rua Maria Jacinta"},
	"33010620": {Estado: "MG", Cidade: "Santa Luzia", Bairro: "Bela Vista", Rua: "Rua Palmor Teixeira Viana"},
	"33045370": {Estado: "MG", Cidade: "Santa Luzia", Bairro: "Frimisa", Rua: "Rua R"},
	"33822720": {Estado: "MG", Cidade: "Ribeirão das Neves", Bairro: "Liberdade", Rua: "Avenida B"},
	"35500538": {Estado: "MG", Cidade: "Divinópolis", Bairro: "Santa Rosa", Rua: "Rua Moscou"},
	"35700292": {Estado: "MG", Cidade: "Sete Lagoas", Bairro: "Canaã", Rua: "Rua Natal"},
	"36774406": {Estado: "MG", Cidade: "Cataguases", Bairro: "Sol Nascente", Rua: "Rua Álvaro Franca"},
	"38400710": {Estado: "MG", Cidade: "Uberlândia", Bairro: "Brasil", Rua: "Avenida Afonso Pena"},
	"38703240": {Estado: "MG", Cidade: "Patos de Minas", Bairro: "Bela Vista", Rua: "Rua Arnaldo Luiz de Oliveira"},
	"39803401": {Estado: "MG", Cidade: "Teófilo Otoni", Bairro: "Jardim São Paulo", Rua: "Rua São Caetano"},
	"44028502": {Estado: "BA", Cidade: "Feira de Santana", Bairro: "Gabriela", Rua: "Rua Professora Maria da Glória"},
	"44054394": {Estado: "BA", Cidade: "Feira de Santana", Bairro: "Parque Ipê", Rua: "Rua Tijuca"},
	"45656220": {Estado: "BA", Cidade: "Ilhéus", Bairro: "Nelson Costa", Rua: "Rua Bem-Me-Quer"},
	"53401000": {Estado: "PE", Cidade: "Paulista", Bairro: "Centro", Rua: "Rua Campo Grande"},
	"54505470": {Estado: "PE", Cidade: "Cabo de Santo Agostinho", Bairro: "Centro", Rua: "Rua Vigário João Batista"},
	"57306370": {Estado: "AL", Cidade: "Arapiraca", Bairro: "Cavaco", Rua: "Rua Manoel Ferreira de Brito"},
	"58832970": {Estado: "PB", Cidade: "Mato Grosso", Bairro: "Centro", Rua: "Rua João Serafim de Lima 96"},
	"71225520": {Estado: "DF", Cidade: "Brasília", Bairro: "Zona Industrial (Guará)", Rua: "Trecho STRC Trecho 2"},
	"72430204": {Estado: "DF", Cidade: "Brasília", Bairro: "Setor Norte (Gama)", Rua: "Quadra 2 Conjunto D"},
	"74910095": {Estado: "GO", Cidade: "Aparecida de Goiânia", Bairro: "Parque Real de Goiânia", Rua: "Avenida São Paulo"},
	"78557165": {Estado: "MT", Cidade: "Sinop", Bairro: "Setor Industrial", Rua: "Rua João Pedro Moreira de Carvalho"},
	"78559889": {Estado: "MT", Cidade: "Sinop", Bairro: "Residencial sabrina III", Rua: "Rua Projetada 2"},
	"78559899": {Estado: "MT", Cidade: "Sinop", Bairro: "Área Rural de Sinop", Rua: "Área Rural"},
	"79106400": {Estado: "MS", Cidade: "Campo Grande", Bairro: "Vila Popular", Rua: "Rua Domingos Aparecido Bissoli"},
	"79116121": {Estado: "MS", Cidade: "Campo Grande", Bairro: "Parque Residencial Azaléia", Rua: "Rua Bauxi"},
	"79630090": {Estado: "MS", Cidade: "Três Lagoas", Bairro: "Jardim das Oliveiras", Rua: "Rua Protázio Garcia Leal"},
	"80410201": {Estado: "PR", Cidade: "Curitiba", Bairro: "Centro", Rua: "Rua Visconde de Nacar"},
	"83823138": {Estado: "PR", Cidade: "Fazenda Rio Grande", Bairro: "Nações", Rua: "Avenida Paraguai"},
	"85501240": {Estado: "PR", Cidade: "Pato Branco", Bairro: "Centro", Rua: "Rua Itacolomi"},
	"85806077": {Estado: "PR", Cidade: "Cascavel", Bairro: "FAG", Rua: "Rua João Kuloski"},
	"85813390": {Estado: "PR", Cidade: "Cascavel", Bairro: "Country", Rua: "Rua Acre"},
	"87112257": {Estado: "PR", Cidade: "Sarandi", Bairro: "Parque Residencial Bela Vista", Rua: "Avenida Amambai"},
	"89226500": {Estado: "SC", Cidade: "Joinville", Bairro: "Jardim Paraíso", Rua: "Estrada Timbé"},
	"95700010": {Estado: "RS", Cidade: "Bento Gonçalves", Bairro: "Centro", Rua: "Rua Marechal Deodoro"},
	"99010000": {Estado: "RS", Cidade: "Passo Fundo", Bairro: "Centro", Rua: "Avenida Brasil"},
	"99010030": {Estado: "RS", Cidade: "Passo Fundo", Bairro: "Centro", Rua: "Rua Morom"},
	"99030010": {Estado: "RS", Cidade: "Passo Fundo", Bairro: "Boqueirão", Rua: "Rua Tonico Silva"},
}
